/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WarrantyImport } from './routes/warranty'
import { Route as IndexImport } from './routes/index'
import { Route as ServicesIndexImport } from './routes/services/index'
import { Route as ServicesServiceIdImport } from './routes/services/$serviceId'

// Create/Update Routes

const WarrantyRoute = WarrantyImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ServicesIndexRoute = ServicesIndexImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRoute,
} as any)

const ServicesServiceIdRoute = ServicesServiceIdImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyImport
      parentRoute: typeof rootRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdImport
      parentRoute: typeof rootRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/warranty': typeof WarrantyRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services': typeof ServicesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/warranty': typeof WarrantyRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services': typeof ServicesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/warranty': typeof WarrantyRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/': typeof ServicesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/warranty' | '/services/$serviceId' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/warranty' | '/services/$serviceId' | '/services'
  id: '__root__' | '/' | '/warranty' | '/services/$serviceId' | '/services/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WarrantyRoute: typeof WarrantyRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WarrantyRoute: WarrantyRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/warranty",
        "/services/$serviceId",
        "/services/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/warranty": {
      "filePath": "warranty.tsx"
    },
    "/services/$serviceId": {
      "filePath": "services/$serviceId.tsx"
    },
    "/services/": {
      "filePath": "services/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
